#! /usr/bin/bash
pipreqs app --savepath requirements.txt --force
read -rp "Notes : " NOTES
if test "$NOTES" == "" ; then
	NOTES="updates of a general nature"
fi
cd ../.. ; git add . ; git commit -am "$NOTES" ;git push ; cd -
